### PR TITLE
Issues connecting to ftp://ftp.ensembl.org/

### PR DESCRIPTION
**Pull request by jwhsanger**
Hi Guys,

I fully expect this pull request to be rejected but am using it as a way of highlighting an issue we had. Currently we hacked it to make it work so this is a very incomplete solution but you might fine it useful for debugging if you are having similar issues.

Jon :)

Trying to connect to: ftp://ftp.ensembl.org/pub/release-80/fasta/homo_sapiens/cdna/

Net::FTP would not list dir contents - added Passive=>1 to new command

LWP::Simple hangs followed by a 404 error - removed altogether and replaced with hacky shell-out to wget. Unable to determine issue here

### CODE REVIEW

**Comment by keiranmraine** [comment]
Don't see any reason to reject, but @AndyMenzies will make the final decision.  I switched to [File::Fetch](http://perldoc.perl.org/File/Fetch.html) in some instances as LWP:Simple was giving truncated results... there's also the one-stop-shop [IO::All](http://search.cpan.org/~ingy/IO-All-0.86/lib/IO/All.pod)

**Comment by AndyMenzies** [comment]
I've never had this script fail on the download or the remote directory look up. Could you let me know which version of perl you were running?

**Comment by keiranmraine** [comment]
Have you ever tried it outside of the Sanger proxy?

**Comment by jwhsanger** [comment]
Oh... Thats interesting... I have made some commits to my fork but it looks like they are now bundled into this request... I had intended to keep them separate. See bug report #10 for details.

**Comment by mcast** [comment]
On Tue, Jul 14, 2015 at 08:16:05AM -0700, jwhsanger wrote:

> Oh... Thats interesting... I have made some commits to my fork but
> it looks like they are now bundled into this request... I had
> intended to keep them separate. See bug report #10 for details.

Pull requests go wrong if you start them from a generic "dev" branch
(I know, I've done it a few times).

Just make a new branch named for your change and put that in the pull
request.  Not sure if you can change it now, might need to abandon
this and start a new one.

-- 
Matthew


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by keiranmraine** [comment]
All commits to the same fork go into the same pull request unless you do branches within the initial fork (hubflow feature branches would be a good way to go).

I mention the proxy as it may need LWP::UserAgent to work properly.

**Comment by jwhsanger** [comment]
I mention the proxy as it may need LWP::UserAgent to work properly.

If I get chance I will give it a go... Let me revisit that branching structure again...

**Comment by jwhsanger** [comment]
Could you let me know
which version of perl you were running?

perl -v v5.18.2

So not terribly ancient, but a little ways behind...

**Pull request closed without merging**
