### PR TITLE
Feature/speed up

### PR DESCRIPTION
**Pull request by keiranmraine**
Relates to #35.

Loading `vagrent.cache.gz` by chromosome into an interval tree and converting the string object representation into an object (and adding `cdnaseq`) only when used the number of disk accesses via tabix are considerably reduced.

This results in a large reduction in run time.

* GRCh37 WGS
  * was _**17**_ min (50MB RAM)
  * now _**9**_ min (120MB/900MB RAM, sorted/unsorted)
* GRCh38 WGS (with e91)
  * was _**76**_ min (50MB RAM)
  * now _**12**_ min (140MB/1GB RAM, sorted/unsorted)

By default the higher memory footprint would be used, unless a `*.tbi` file is detected for the input.  User can indicate input is sorted with `-s` option.

### CODE REVIEW

**Comment by keiranmraine** [comment]
GRCh37 WGS verification (982,427 variants):

```
$ diff -qs full-GRCh37-stable.vcf full-GRCh37-loci-data3.vcf
Files full-GRCh37-stable.vcf and full-GRCh37-loci-data3.vcf are identical

# sorted input , trimmed output to relevant info
$ diff -y --suppress-common-lines full-GRCh37-stable.time full-GRCh37-loci-data3.time
	User time (seconds): 1052.81			      |		User time (seconds): 526.13
	System time (seconds): 16.33			      |		System time (seconds): 2.89
	Elapsed (wall clock) time (h:mm:ss or m:ss): 17:48.37 |		Elapsed (wall clock) time (h:mm:ss or m:ss): 8:48.48
	Maximum resident set size (kbytes): 47304	      |		Maximum resident set size (kbytes): 115720
```

GRCh38 WGS verification (1,010,149 variants):

```
$ diff -qs full-GRCh38-stable.vcf full-GRCh38-loci-data3.vcf 
Files full-GRCh38-stable.vcf and full-GRCh38-loci-data3.vcf are identical

$ diff -y --suppress-common-lines full-GRCh38-stable.time full-GRCh38-loci-data3.time
	User time (seconds): 4522.99			      |		User time (seconds): 694.12
	System time (seconds): 44.09			      |		System time (seconds): 3.92
	Elapsed (wall clock) time (h:mm:ss or m:ss): 1:16:05  |		Elapsed (wall clock) time (h:mm:ss or m:ss): 11:36.27
	Maximum resident set size (kbytes): 49916	      |		Maximum resident set size (kbytes): 138848
```

**Comment by keiranmraine** [comment]
These examples were for cgpPindel (in/del) VCF files, need to also assess CaVEMan (snv)

**Comment by AndyMenzies** [comment]
The code looks good and the change in performance is great, but we do need a caveman test before we merge this in.

**Comment by keiranmraine** [comment]
I'll do all of that within the internal CI stuff, don't merge just yet.

**Pull request merged**
